@echo off
echo Starting Konsultabot Mobile App...
cd /d "c:\Users\Ace Ziegfred Culapas\CascadeProjects\Project\KonsultabotMobileNew"
echo Installing dependencies...
npm install
echo Starting Expo development server...
npx expo start
pause
